sequenceDiagram
    participant Пользователь
    participant Keycloak
    participant Сервис
    participant БД

    Пользователь ->>+ Keycloak: Аутентификация
    Keycloak -->>- Пользователь: Вход выполнен
    alt
        Keycloak -->> Пользователь: Неверный логин или пароль
    end

    Пользователь ->>+ Keycloak: Создание учетной записи для заказчика
    Keycloak -->>- Пользователь: Учетная запись создана

    Пользователь ->>+ Сервис: Создание заявки на СабаКо
    Сервис ->>- БД: Сохранение заявки
    БД -->>+ Сервис: Заказ сохранен
    Сервис -->>- Пользователь: Заявки передан на сборку
