sequenceDiagram
    participant Пользователь
    participant Auth Manager
    participant Keycloak
    participant KeycloakClient
    participant Endpoints
    participant OrderController
    participant OrderService
    participant Postrges

    Пользователь ->>+ Endpoints: Запрос на аутентификацию

    Endpoints ->>- Auth Manager: Вызов метода getToken
    Auth Manager ->>+ KeycloakClient: Вызов метода getAuthTokenBySecret

    KeycloakClient ->>+ Keycloak: Вызов keycloak/auth
    Keycloak ->>+ Пользователь: Редирект на страницу входа
    Пользователь ->>- Keycloak: Ввод логина и пароля

    alt
        Keycloak -->> Пользователь:ерный логин или пароль
    end

    Keycloak -->> Пользователь: Редирект на главную страницу

    Keycloak ->>+ KeycloakClient: Передает токен
    KeycloakClient ->>- Auth Manager: Получен токен
    Auth Manager ->>+  Endpoints: Получен токен

    Пользователь ->>+ Endpoints: Создание учетной записи для заказчика

    Endpoints ->>- OrderController: Вызов метода create
    alt
        OrderController -->> Пользователь: Ошибка заполнения заявки
    end
    OrderController ->>+ OrderService: Вызов метода create
    OrderService ->>+ Postrges: Сохранение заявки в БД
    Postrges ->>- OrderService: Успешное сохранение
    OrderService ->>- OrderController: Заявка сохранена в бд
    OrderController ->> Пользователь: Заявка создана
