sequenceDiagram
    participant Пользователь
    participant Keycloak
    participant Сервер
    participant БД

    Пользователь ->>+ Keycloak: Аутентификация
    Keycloak -->>- Пользователь: Вход выполнен
    alt
        Keycloak -->> Пользователь: Неверный логин или пароль
    end

    Пользователь ->>+ Keycloak: Создание учетной записи для заказчика
    Keycloak -->>- Пользователь: Учетная запись создана

    Пользователь ->>+ Сервер: Создание заявки на СабаКо
    Сервер ->>- БД: Сохранение заявки
    БД -->>+ Сервер: Заказ сохранен
    Сервер -->>- Пользователь: Заявки передан на сборку
