global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: tarantool
    static_configs:
      - targets:
        - "host.docker.internal:8081"
        - "host.docker.internal:8082"
        - "host.docker.internal:8083"
        - "host.docker.internal:8084"
        - "host.docker.internal:8085"
    metrics_path: "/metrics"
